version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scam_dev
    ports:
      - "5432:5432"
    volumes:
        - ./postgres-data:/home/wejman/AGH/BiteHack/scam-data
